modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/Roll-Out/Soulify-Forge/issues"
[[mods]]
modId="soulify"
version="1.0.0"
displayName="Soulify"
logoFile="soulify.png"
credits="8HP"
authors="Steven's Hideout"
description='''

'''

[[dependencies.soulify]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.soulify]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.soulify]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"